"""Updated relationships to fix overlaps

Revision ID: 761b64b14aa1
Revises: 082c8679e914
Create Date: 2024-10-29 22:26:14.815850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '761b64b14aa1'
down_revision = '082c8679e914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
