"""Updated relationships to fix overlaps

Revision ID: 7cacd153a0c2
Revises: 761b64b14aa1
Create Date: 2024-10-29 22:34:07.087160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cacd153a0c2'
down_revision = '761b64b14aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
